### ISSUE TITLE
Legacy autograd function with non-static forward method is deprecated

### ISSUE THREAD

**Issue by trougnouf** [jorge-pessoa/pytorch-gdn#2]
I get many of these errors
`/build/python-pytorch/src/pytorch-1.3.1-opt-cuda/torch/csrc/autograd/python_function.cpp:620: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)`

Likely from the LowerBound(Function) class. Luckily it still works in pytorch -1.3.1

**Comment by jorge-pessoa** [comment]
Thanks for noting. I will take a look at this.

**Comment by prasangadhungel** [comment]
Simply use static forward and backward method in LowerBound function and call it with `LowerBound.apply(self.beta, self.beta_bound)` in forward function of GDN
