### ISSUE TITLE
LowerBound purpose unclear

### ISSUE THREAD

**Issue by rfeinman** [jorge-pessoa/pytorch-gdn#3]
What is the point of your LowerBound custom autograd function? Is the functionality different than standard `torch.max(x, b)` or `F.threshold(x,b,b)`? I don't see a situation where your variable `pass_through_2` in .backward() would ever be true (unless you have a negative reparam_offset).

**Comment by jorge-pessoa** [comment]
The only practical difference as you said is to support the complete range of reparam_offset values.
