### ISSUE TITLE
Correct for GDN's math equation

### ISSUE THREAD

**Issue by ZhangYuef** [jorge-pessoa/pytorch-gdn#4]
Hi, thanks for sharing! I found a little mistake in your comment of GDN's math equation. In my opinion, the `x` has been squared.

In your code:
https://github.com/jorge-pessoa/pytorch-gdn/blob/1410686a67e7de45ff21de92a0d5c35de7c26d09/pytorch_gdn/__init__.py#L31

IMO this equation should be
```
y[i] = x[i] / sqrt(beta[i] + sum_j(gamma[j, i] * x[j]^2))
```

Please check for this.

**Comment by jorge-pessoa** [comment]
Thank you for spotting this difference, I will correct this promptly. This is only a typo in the comment as the implementation seems to correctly square the inputs.
